### ISSUE TITLE
1.3.5 - no data

### ISSUE THREAD

**Issue by HaSchuk** [Martvvliet/homebridge-mi-flora-filtered#10]
Changes in this line compared to 1.3.4 Lead to no data:

if (data.deviceId == that.deviceId) {
            that.log("Lux: %s, Temperature: %s, Moisture: %s, Fertility: %s", data.lux, data.temperature, data.moisture, data.fertility);

Neither in log nor Eve App. 

In contrast 

 if (data.deviceId = that.deviceId) {
            that.log("Firmware: %s, Battery level: %s", data.firmwareVersion, data.batteryLevel);
            that.storedData.firmware = data;

gives data in log and App.

**Comment by Martvvliet** [comment]
@HaSchuk Thanks for reporting. Was an issue with the update, so rolled back the update. Version 1.3.4 is the latest again.
