### ISSUE TITLE
Support for hoobs non root?

### ISSUE THREAD

**Issue by GitGabKat** [Martvvliet/homebridge-mi-flora-filtered#13]
I tried a lot using your plugin within hoobs. Unfortunately I don't get any data from the sensor, even it is shown in the home app. The reason seems to be that I run Homebridge as a hoobs instance. For security purposes not with root rights but as hoobsadmin. That's the typical way how to run hoobs and there is absolutely no issue doing so with other plugins. To proof if the rights are the problem, I even run hoobs in a different instance with roots rights and the data was displayed. However I would prefer to run hoobs still not as root. 

Are you able to improve the plugin in that way that it catches the data even without run Homebridge as root user? Thank you in advance!

**Comment by Martvvliet** [comment]
Sorry for the late response, As far as I know, you need these rights for the Bluetooth communications. As I only ported the plugin to make it work again, I'm not sure if it is possible to make it run without root support. 

Also when you run the Pi only for your homebridge, running as root is not really an issue, but that is your choice of course. Sorry, I can't help you any further.
