### ISSUE TITLE
Is there support for the "Xiaomi Smart Flower Pot Flora"/Ropot?

### ISSUE THREAD

**Issue by andreasfrank** [Martvvliet/homebridge-mi-flora-filtered#6]
Sorry for the question, but i couldn't find this Xiaomi device (Description: https://www.xiaomitoday.com/xiaomi-smart-flower-pot-flora-review/ ) in your list of supported devices. In the Mi Home app this device is called Ropot (availbale only with location China).
Is it supported or do you plan to support these flower pots?

Thx & Kind regards
Andreas

**Comment by Martvvliet** [comment]
Hi Andreas, Thank you for your interest. I only copied the plugin and made sure that it was filtered and working with the latest version of Node, I didn't really investigate how to add support for devices. So I can't help you with this. sorry.
Good luck with finding something that does work :)
Regards, Mart
